# Generated by Django 3.1.2 on 2022-11-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='quantity',
        ),
    ]
