# Generated by Django 3.1.2 on 2022-11-19 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20221119_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='scope',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='Tags',
            field=models.ManyToManyField(through='articles.Scope', to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.TextField(verbose_name='Тег'),
        ),
    ]
