# Generated by Django 3.1.2 on 2022-11-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20221119_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='Tags',
            field=models.ManyToManyField(through='articles.Scope', to='articles.Article'),
        ),
    ]
