# Generated by Django 3.1.2 on 2022-11-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_tag_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Связан', 'verbose_name_plural': 'Связан'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
