# Generated by Django 3.1.2 on 2022-11-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20221119_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='Tags',
        ),
        migrations.DeleteModel(
            name='Scope',
        ),
    ]
