# Generated by Django 3.1.2 on 2022-11-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20221119_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='articles',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='scope',
            old_name='tags',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='tags',
        ),
    ]
