# Generated by Django 3.1.2 on 2022-11-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20221119_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Scope',
        ),
    ]
