# Generated by Django 3.1.2 on 2022-11-19 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_auto_20221119_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_tag', to='articles.article')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_tag', to='articles.tag')),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='tags',
            field=models.ManyToManyField(through='articles.Scope', to='articles.Article'),
        ),
    ]
