# Generated by Django 3.1.2 on 2022-11-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_auto_20221119_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tags',
            field=models.ManyToManyField(related_name='Tags', through='articles.Scope', to='articles.Article'),
        ),
    ]
