# Generated by Django 3.1.2 on 2022-11-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_auto_20221119_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Scope',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
